# Generated by Django 5.1.1 on 2024-09-23 11:51

import Driver.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUserModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='driver', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nid', models.IntegerField(validators=[Driver.models.validate_nid])),
                ('phone_number', models.CharField(max_length=15, validators=[Driver.models.validate_phone_number])),
                ('driving_license_no', models.CharField(max_length=15, validators=[Driver.models.validate_driving_license_no])),
                ('user_photo', models.URLField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('has_car', models.BooleanField(default=False)),
            ],
        ),
    ]
