# Generated by Django 5.1.1 on 2024-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderusermodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riderusermodel',
            name='user_photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
